import 'dart:developer';

import 'package:dropdown_search/dropdown_search.dart';
import 'package:chip_list/chip_list.dart';
import 'package:medcore/Patient-PhysicianScreens/home_screen.dart';
import 'package:medcore/Patient-PhysicianScreens/SearchSymptoms/search_results.dart';
import 'package:medcore/Utiils/colors.dart';
import 'package:medcore/Utiils/common_widgets.dart';
import 'package:medcore/Utiils/text_font_family.dart';
import 'package:medcore/main.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../../AuthScreens/signin_screen.dart';
import 'dart:async';
import 'dart:convert';
import 'package:http/http.dart' as http;
import 'dart:convert' as convert;

var symptoms = const [
  "shortness of breath",
  "dizziness",
  "asthenia",
  "fall",
  "syncope",
  "vertigo",
  "sweat",
  "sweating increased",
  "palpitation",
  "nausea",
  "angina pectoris",
  "pressure chest",
  "polyuria",
  "polydypsia",
  "pain chest",
  "orthopnea",
  "rale",
  "unresponsiveness",
  "mental status changes",
  "vomiting",
  "labored breathing",
  "feeling suicidal",
  "suicidal",
  "hallucinations auditory",
  "feeling hopeless",
  "weepiness",
  "sleeplessness",
  "motor retardation",
  "irritable mood",
  "blackout",
  "mood depressed",
  "hallucinations visual",
  "worry",
  "agitation",
  "tremor",
  "intoxication",
  "verbal auditory hallucinations",
  "energy increased",
  "difficulty",
  "nightmare",
  "unable to concentrate",
  "homelessness",
  "hypokinesia",
  "dyspnea on exertion",
  "chest tightness",
  "cough",
  "fever", ////
  "decreased translucency",
  "productive cough",
  "pleuritic pain",
  "yellow sputum",
  "breath sounds decreased",
  "chill",
  "rhonchus",
  "green sputum",
  "non-productive cough",
  "wheezing",
  "haemoptysis",
  "distress respiratory",
  "tachypnea",
  "malaise",
  "night sweat",
  "jugular venous distention",
  "dyspnea",
  "dysarthria",
  "speech slurred",
  "facial paresis",
  "hemiplegia",
  "seizure",
  "numbness",
  "symptom aggravating factors",
  "st segment elevation",
  "st segment depression",
  "t wave inverted",
  "presence of q wave",
  "chest discomfort",
  "bradycardia",
  "pain",
  "nonsmoker",
  "erythema",
  "hepatosplenomegaly",
  "pruritus",
  "diarrhea",
  "abscess bacterial",
  "swelling",
  "apyrexial",
  "dysuria",
  "hematuria",
  "renal angle tenderness",
  "lethargy",
  "hyponatremia",
  "hemodynamically stable",
  "difficulty passing urine",
  "consciousness clear",
  "guaiac positive",
  "monoclonal",
  "ecchymosis",
  "tumor cell invasion",
  "haemorrhage",
  "pallor",
  "fatigue",
  "heme positive",
  "pain back",
  "orthostasis",
  "arthralgia",
  "transaminitis",
  "sputum purulent",
  "hypoxemia",
  "hypercapnia",
  "patient non compliance",
  "unconscious state",
  "bedridden",
  "abdominal tenderness",
  "unsteady gait",
  "hyperkalemia",
  "urgency of micturition",
  "ascites",
  "hypotension",
  "enuresis",
  "asterixis",
  "muscle twitch",
  "sleepy",
  "headache",
  "lightheadedness",
  "food intolerance",
  "numbness of hand",
  "general discomfort",
  "drowsiness",
  "stiffness",
  "prostatism",
  "weight gain",
  "tired",
  "mass of body structure",
  "has religious belief",
  "nervousness",
  "formication",
  "hot flush",
  "lesion",
  "cushingoid facies",
  "cushingoid habitus",
  "emphysematous change",
  "decreased body weight",
  "hoarseness",
  "thicken",
  "pulsus paradoxus",
  "gravida 10",
  "heartburn",
  "pain abdominal",
  "dullness",
  "spontaneous rupture of membranes",
  "muscle hypotonia",
  "hypotonic",
  "redness",
  "hypesthesia",
  "hyperacusis",
  "scratch marks",
  "sore to touch",
  "burning sensation",
  "satiety early",
  "throbbing sensation quality",
  "sensory discomfort",
  "constipation",
  "breech presentation",
  "cyanosis",
  "pain in lower limb",
  "cardiomegaly",
  "clonus",
  "unwell",
  "anorexia",
  "history of - blackout",
  "anosmia",
  "metastatic lesion",
  "hemianopsia homonymous",
  "hematocrit decreased",
  "neck stiffness",
  "cicatrisation",
  "hypometabolism",
  "aura",
  "myoclonus",
  "gurgle",
  "wheelchair bound",
  "left atrial hypertrophy",
  "oliguria",
  "catatonia",
  "unhappy",
  "paresthesia",
  "gravida 0",
  "lung nodule",
  "distended abdomen",
  "ache",
  "macerated skin",
  "heavy feeling",
  "rest pain",
  "sinus rhythm",
  "withdraw",
  "behavior hyperactive",
  "terrify",
  "photopsia",
  "giddy mood",
  "disturbed family",
  "hypersomnia",
  "hyperhidrosis disorder",
  "mydriasis",
  "extrapyramidal sign",
  "loose associations",
  "exhaustion",
  "snore",
  "r wave feature",
  "overweight",
  "systolic murmur",
  "asymptomatic",
  "splenomegaly",
  "bleeding of vagina",
  "macule",
  "photophobia",
  "painful swallowing",
  "cachexia",
  "hypocalcemia result",
  "hypothermia, natural",
  "atypia",
  "general unsteadiness",
  "throat sore",
  "snuffle",
  "hacking cough",
  "stridor",
  "paresis",
  "aphagia",
  "focal seizures",
  "abnormal sensation",
  "stupor",
  "fremitus",
  "Stahli's line",
  "stinging sensation",
  "paralyse",
  "hirsutism",
  "sniffle",
  "bradykinesia",
  "out of breath",
  "urge incontinence",
  "vision blurred",
  "room spinning",
  "rambling speech",
  "clumsiness",
  "decreased stool caliber",
  "hematochezia",
  "egophony",
  "scar tissue",
  "neologism",
  "decompensation",
  "stool color yellow",
  "rigor - temperature-associated observation",
  "paraparesis",
  "moody",
  "fear of falling",
  "spasm",
  "hyperventilation",
  "excruciating pain",
  "gag",
  "posturing",
  "pulse absent",
  "dysesthesia",
  "polymyalgia",
  "passed stones",
  "qt interval prolonged",
  "ataxia",
  "Heberden's node",
  "hepatomegaly",
  "sciatica",
  "frothy sputum",
  "mass in breast",
  "retropulsion",
  "estrogen use",
  "hypersomnolence",
  "underweight",
  "red blotches",
  "colic abdominal",
  "hypokalemia",
  "hunger",
  "prostate tender",
  "pain foot",
  "urinary hesitation",
  "disequilibrium",
  "flushing",
  "indifferent mood",
  "urinoma",
  "hypoalbuminemia",
  "pustule",
  "slowing of urinary stream",
  "extreme exhaustion",
  "no status change",
  "breakthrough pain",
  "pansystolic murmur",
  "systolic ejection murmur",
  "stuffy nose",
  "barking cough",
  "rapid shallow breathing",
  "noisy respiration",
  "nasal discharge present",
  "frail",
  "cystic lesion",
  "projectile vomiting",
  "heavy legs",
  "titubation",
  "dysdiadochokinesia",
  "achalasia",
  "side pain",
  "monocytosis",
  "posterior rhinorrhea",
  "incoherent",
  "lameness",
  "claudication",
  "clammy skin",
  "mediastinal shift",
  "nausea and vomiting",
  "awakening early",
  "tenesmus",
  "fecaluria",
  "pneumatouria",
  "todd paralysis",
  "alcoholic withdrawal symptoms",
  "myalgia",
  "dyspareunia",
  "poor dentition",
  "floppy",
  "inappropriate affect",
  "poor feeding",
  "moan",
  "welt",
  "tinnitus",
  "hydropneumothorax",
  "superimposition",
  "feeling strange",
  "uncoordination",
  "absences finding",
  "tonic seizures",
  "debilitation",
  "impaired cognition",
  "drool",
  "pin-point pupils",
  "tremor resting",
  "groggy",
  "adverse reaction",
  "adverse effect",
  "abdominal bloating",
  "fatigability",
  "para 2",
  "abortion",
  "intermenstrual heavy bleeding",
  "previous pregnancies 2",
  "primigravida",
  "abnormally hard consistency",
  "proteinemia",
  "pain neck",
  "dizzy spells",
  "shooting pain",
  "hyperemesis",
  "milky",
  "regurgitates after swallowing",
  "lip smacking",
  "phonophobia",
  "rolling of eyes",
  "ambidexterity",
  "bruit",
  "breath-holding spell",
  "scleral icterus",
  "retch",
  "blanch",
  "elation",
  "verbally abusive behavior",
  "transsexual",
  "behavior showing increased motor activity",
  "coordination abnormal",
  "choke",
  "bowel sounds decreased",
  "no known drug allergies",
  "low back pain",
  "charleyhorse",
  "sedentary",
  "feels hot/feverish",
  "flare",
  "pericardial friction rub",
  "hoard",
  "panic",
  "cardiovascular finding",
  "cardiovascular event",
  "soft tissue swelling",
  "rhd positive",
  "para 1",
  "nasal flaring",
  "sneeze",
  "hypertonicity",
  "Murphy's sign",
  "flatulence",
  "gasping for breath",
  "feces in rectum",
  "prodrome",
  "hypoproteinemia",
  "alcohol binge episode",
  "abdomen acute",
  "air fluid level",
  "catching breath",
  "large-for-dates fetus",
  "immobile",
  "homicidal thoughts"
];
var zero = [];
bool empty = false;
List<String> selectedSymptoms = [];
List<int> commonSymptoms = [];

class SearchScreen extends StatefulWidget {
  @override
  State<SearchScreen> createState() => _SearchScreenState();
}

Future<http.Response> postData(name) {
  return http.post(
    Uri.parse('http://10.0.2.2:5000/'),
    headers: <String, String>{
      'Content-Type': 'application/json; charset=UTF-8',
    },
    body: jsonEncode(<String, List<dynamic>>{
      'name': name,
    }),
  );
}

class _SearchScreenState extends State<SearchScreen> {
  // SearchScreen({Key? key}) : super(key: key);
  String greating = '';

  @override
  Widget build(BuildContext context) {
    // selectedSymptoms.add('fever');
    return GestureDetector(
      onTap: () {
        FocusScopeNode currentFocus = FocusScope.of(context);

        if (!currentFocus.hasPrimaryFocus) {
          currentFocus.unfocus();
        }
      },
      child: Scaffold(
          backgroundColor: ColorResources.whiteF6F,
          resizeToAvoidBottomInset: false,
          body: SingleChildScrollView(
            child: ScrollConfiguration(
              behavior: MyBehavior(),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.start,
                children: [
                  HeaderWidget(),
                  Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
                    heavyText(
                        "   Most common symptoms", ColorResources.grey777, 15),
                  ]),
                  // Wrap(
                  //     spacing: 8.0, // gap between adjacent chips
                  //     runSpacing: 4.0, // gap between lines
                  // children: [
                  SizedBox(height: 2),
                  ChipList(
                    mainAxisAlignment: MainAxisAlignment.start,
                    shouldWrap: true,
                    style: TextStyle(fontWeight: FontWeight.bold),
                    listOfChipNames: [
                      'fever',
                      'headache',
                      'throat sore',
                      'shortness of breath',
                      'cough',
                    ],
                    supportsMultiSelect: true,
                    activeBgColorList: [
                      Color.fromARGB(183, 117, 197, 197).withOpacity(0.6),
                      Color.fromARGB(183, 117, 197, 197).withOpacity(0.6),
                      Color.fromARGB(183, 117, 197, 197).withOpacity(0.6),
                      Color.fromARGB(183, 117, 197, 197).withOpacity(0.6),
                      Color.fromARGB(183, 117, 197, 197).withOpacity(0.6),
                    ],
                    inactiveBgColorList: [ColorResources.whiteF6F],
                    activeTextColorList: [Colors.black],
                    inactiveTextColorList: [Colors.black],

                    listOfChipIndicesCurrentlySeclected: commonSymptoms,
                    inactiveBorderColorList: [
                      Color.fromARGB(183, 117, 197, 197).withOpacity(0.6),
                    ],
                    //  borderColorList: const [Colors.pink, Colors.yellow, Colors.green,Colors.yellow, Colors.green],
                  ),
                  //  ]),

                  SizedBox(height: 6),
                  Container(
                    width: 360,
                    child: Theme(
                        data: ThemeData(
                          primarySwatch: Colors.teal,
                          materialTapTargetSize:
                              MaterialTapTargetSize.shrinkWrap,
                          // inputDecorationTheme: InputDecorationTheme()
                        ),
                        child: DropdownSearch<String>.multiSelection(
                          enabled: true,
                          selectedItems: selectedSymptoms,
                          items: [
                            "dizziness",
                            "asthenia",
                            "fall",
                            "syncope",
                            "vertigo",
                            "sweat",
                            "sweating increased",
                            "palpitation",
                            "nausea",
                            "angina pectoris",
                            "pressure chest",
                            "polyuria",
                            "polydypsia",
                            "pain chest",
                            "orthopnea",
                            "rale",
                            "unresponsiveness",
                            "mental status changes",
                            "vomiting",
                            "labored breathing",
                            "feeling suicidal",
                            "suicidal",
                            "hallucinations auditory",
                            "feeling hopeless",
                            "weepiness",
                            "sleeplessness",
                            "motor retardation",
                            "irritable mood",
                            "blackout",
                            "mood depressed",
                            "hallucinations visual",
                            "worry",
                            "agitation",
                            "tremor",
                            "intoxication",
                            "verbal auditory hallucinations",
                            "energy increased",
                            "difficulty",
                            "nightmare",
                            "unable to concentrate",
                            "homelessness",
                            "hypokinesia",
                            "dyspnea on exertion",
                            "chest tightness",
                            "decreased translucency",
                            "productive cough",
                            "pleuritic pain",
                            "yellow sputum",
                            "breath sounds decreased",
                            "chill",
                            "rhonchus",
                            "green sputum",
                            "non-productive cough",
                            "wheezing",
                            "haemoptysis",
                            "distress respiratory",
                            "tachypnea",
                            "malaise",
                            "night sweat",
                            "jugular venous distention",
                            "dyspnea",
                            "dysarthria",
                            "speech slurred",
                            "facial paresis",
                            "hemiplegia",
                            "seizure",
                            "numbness",
                            "symptom aggravating factors",
                            "st segment elevation",
                            "st segment depression",
                            "t wave inverted",
                            "presence of q wave",
                            "chest discomfort",
                            "bradycardia",
                            "pain",
                            "nonsmoker",
                            "erythema",
                            "hepatosplenomegaly",
                            "pruritus",
                            "diarrhea",
                            "abscess bacterial",
                            "swelling",
                            "apyrexial",
                            "dysuria",
                            "hematuria",
                            "renal angle tenderness",
                            "lethargy",
                            "hyponatremia",
                            "hemodynamically stable",
                            "difficulty passing urine",
                            "consciousness clear",
                            "guaiac positive",
                            "monoclonal",
                            "ecchymosis",
                            "tumor cell invasion",
                            "haemorrhage",
                            "pallor",
                            "fatigue",
                            "heme positive",
                            "pain back",
                            "orthostasis",
                            "arthralgia",
                            "transaminitis",
                            "sputum purulent",
                            "hypoxemia",
                            "hypercapnia",
                            "patient non compliance",
                            "unconscious state",
                            "bedridden",
                            "abdominal tenderness",
                            "unsteady gait",
                            "hyperkalemia",
                            "urgency of micturition",
                            "ascites",
                            "hypotension",
                            "enuresis",
                            "asterixis",
                            "muscle twitch",
                            "sleepy",
                            "lightheadedness",
                            "food intolerance",
                            "numbness of hand",
                            "general discomfort",
                            "drowsiness",
                            "stiffness",
                            "prostatism",
                            "weight gain",
                            "tired",
                            "mass of body structure",
                            "has religious belief",
                            "nervousness",
                            "formication",
                            "hot flush",
                            "lesion",
                            "cushingoid facies",
                            "cushingoid habitus",
                            "emphysematous change",
                            "decreased body weight",
                            "hoarseness",
                            "thicken",
                            "pulsus paradoxus",
                            "gravida 10",
                            "heartburn",
                            "pain abdominal",
                            "dullness",
                            "spontaneous rupture of membranes",
                            "muscle hypotonia",
                            "hypotonic",
                            "redness",
                            "hypesthesia",
                            "hyperacusis",
                            "scratch marks",
                            "sore to touch",
                            "burning sensation",
                            "satiety early",
                            "throbbing sensation quality",
                            "sensory discomfort",
                            "constipation",
                            "breech presentation",
                            "cyanosis",
                            "pain in lower limb",
                            "cardiomegaly",
                            "clonus",
                            "unwell",
                            "anorexia",
                            "history of - blackout",
                            "anosmia",
                            "metastatic lesion",
                            "hemianopsia homonymous",
                            "hematocrit decreased",
                            "neck stiffness",
                            "cicatrisation",
                            "hypometabolism",
                            "aura",
                            "myoclonus",
                            "gurgle",
                            "wheelchair bound",
                            "left atrial hypertrophy",
                            "oliguria",
                            "catatonia",
                            "unhappy",
                            "paresthesia",
                            "gravida 0",
                            "lung nodule",
                            "distended abdomen",
                            "ache",
                            "macerated skin",
                            "heavy feeling",
                            "rest pain",
                            "sinus rhythm",
                            "withdraw",
                            "behavior hyperactive",
                            "terrify",
                            "photopsia",
                            "giddy mood",
                            "disturbed family",
                            "hypersomnia",
                            "hyperhidrosis disorder",
                            "mydriasis",
                            "extrapyramidal sign",
                            "loose associations",
                            "exhaustion",
                            "snore",
                            "r wave feature",
                            "overweight",
                            "systolic murmur",
                            "asymptomatic",
                            "splenomegaly",
                            "bleeding of vagina",
                            "macule",
                            "photophobia",
                            "painful swallowing",
                            "cachexia",
                            "hypocalcemia result",
                            "hypothermia, natural",
                            "atypia",
                            "general unsteadiness",
                            "snuffle",
                            "hacking cough",
                            "stridor",
                            "paresis",
                            "aphagia",
                            "focal seizures",
                            "abnormal sensation",
                            "stupor",
                            "fremitus",
                            "Stahli's line",
                            "stinging sensation",
                            "paralyse",
                            "hirsutism",
                            "sniffle",
                            "bradykinesia",
                            "out of breath",
                            "urge incontinence",
                            "vision blurred",
                            "room spinning",
                            "rambling speech",
                            "clumsiness",
                            "decreased stool caliber",
                            "hematochezia",
                            "egophony",
                            "scar tissue",
                            "neologism",
                            "decompensation",
                            "stool color yellow",
                            "rigor - temperature-associated observation",
                            "paraparesis",
                            "moody",
                            "fear of falling",
                            "spasm",
                            "hyperventilation",
                            "excruciating pain",
                            "gag",
                            "posturing",
                            "pulse absent",
                            "dysesthesia",
                            "polymyalgia",
                            "passed stones",
                            "qt interval prolonged",
                            "ataxia",
                            "Heberden's node",
                            "hepatomegaly",
                            "sciatica",
                            "frothy sputum",
                            "mass in breast",
                            "retropulsion",
                            "estrogen use",
                            "hypersomnolence",
                            "underweight",
                            "red blotches",
                            "colic abdominal",
                            "hypokalemia",
                            "hunger",
                            "prostate tender",
                            "pain foot",
                            "urinary hesitation",
                            "disequilibrium",
                            "flushing",
                            "indifferent mood",
                            "urinoma",
                            "hypoalbuminemia",
                            "pustule",
                            "slowing of urinary stream",
                            "extreme exhaustion",
                            "no status change",
                            "breakthrough pain",
                            "pansystolic murmur",
                            "systolic ejection murmur",
                            "stuffy nose",
                            "barking cough",
                            "rapid shallow breathing",
                            "noisy respiration",
                            "nasal discharge present",
                            "frail",
                            "cystic lesion",
                            "projectile vomiting",
                            "heavy legs",
                            "titubation",
                            "dysdiadochokinesia",
                            "achalasia",
                            "side pain",
                            "monocytosis",
                            "posterior rhinorrhea",
                            "incoherent",
                            "lameness",
                            "claudication",
                            "clammy skin",
                            "mediastinal shift",
                            "nausea and vomiting",
                            "awakening early",
                            "tenesmus",
                            "fecaluria",
                            "pneumatouria",
                            "todd paralysis",
                            "alcoholic withdrawal symptoms",
                            "myalgia",
                            "dyspareunia",
                            "poor dentition",
                            "floppy",
                            "inappropriate affect",
                            "poor feeding",
                            "moan",
                            "welt",
                            "tinnitus",
                            "hydropneumothorax",
                            "superimposition",
                            "feeling strange",
                            "uncoordination",
                            "absences finding",
                            "tonic seizures",
                            "debilitation",
                            "impaired cognition",
                            "drool",
                            "pin-point pupils",
                            "tremor resting",
                            "groggy",
                            "adverse reaction",
                            "adverse effect",
                            "abdominal bloating",
                            "fatigability",
                            "para 2",
                            "abortion",
                            "intermenstrual heavy bleeding",
                            "previous pregnancies 2",
                            "primigravida",
                            "abnormally hard consistency",
                            "proteinemia",
                            "pain neck",
                            "dizzy spells",
                            "shooting pain",
                            "hyperemesis",
                            "milky",
                            "regurgitates after swallowing",
                            "lip smacking",
                            "phonophobia",
                            "rolling of eyes",
                            "ambidexterity",
                            "bruit",
                            "breath-holding spell",
                            "scleral icterus",
                            "retch",
                            "blanch",
                            "elation",
                            "verbally abusive behavior",
                            "transsexual",
                            "behavior showing increased motor activity",
                            "coordination abnormal",
                            "choke",
                            "bowel sounds decreased",
                            "no known drug allergies",
                            "low back pain",
                            "charleyhorse",
                            "sedentary",
                            "feels hot/feverish",
                            "flare",
                            "pericardial friction rub",
                            "hoard",
                            "panic",
                            "cardiovascular finding",
                            "cardiovascular event",
                            "soft tissue swelling",
                            "rhd positive",
                            "para 1",
                            "nasal flaring",
                            "sneeze",
                            "hypertonicity",
                            "Murphy's sign",
                            "flatulence",
                            "gasping for breath",
                            "feces in rectum",
                            "prodrome",
                            "hypoproteinemia",
                            "alcohol binge episode",
                            "abdomen acute",
                            "air fluid level",
                            "catching breath",
                            "large-for-dates fetus",
                            "immobile",
                            "homicidal thoughts"
                          ],
                          popupProps: PopupPropsMultiSelection.menu(
                            showSearchBox: true,
                            showSelectedItems: true,
                            searchFieldProps: TextFieldProps(
                                decoration: InputDecoration(
                                    hintText: 'Search..',
                                    constraints:
                                        BoxConstraints(maxHeight: 40))),
                            constraints: BoxConstraints(maxHeight: 500),
                            scrollbarProps:
                                ScrollbarProps(thumbVisibility: true),
                          ),
                          dropdownDecoratorProps: DropDownDecoratorProps(
                            dropdownSearchDecoration: InputDecoration(
                              hintText: "Select symptoms",
                              hintStyle:
                                  TextStyle(color: ColorResources.grey777),
                              enabledBorder: UnderlineInputBorder(
                                borderSide: empty == false
                                    ? const BorderSide(
                                        color: ColorResources.greyA0A, width: 1)
                                    : const BorderSide(
                                        color: Colors.red, width: 1),
                              ),
                            ),
                          ),
                          onChanged: (List<String> selectedValue) {
                            //   // hospitals = selectedValue;

                            selectedSymptoms = selectedValue;
                          },
                        )),
                  ),
                  SizedBox(
                    height: 3,
                  ),
                  if (empty)
                    Row(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          heavyText("    Please select one symptom at least",
                              Colors.red, 14),
                        ]),
                  // Spacer(),
                  Padding(
                    padding: EdgeInsets.symmetric(horizontal: 24, vertical: 40),
                    child: InkWell(
                      onTap: () async {
                        setState(() {
                          selectedSymptoms.length == 0 &&
                                  commonSymptoms.length == 0
                              ? empty = true
                              : empty = false;
                        });
                        if (empty == false) {
                          onsubmit();
                          Get.to(SearchResults());
                        }

                        var data = await postData(zero);
                        log(data.body);
                      },
                      child: Container(
                        height: 50,
                        width: Get.width,
                        decoration: BoxDecoration(
                          color: ColorResources.green,
                          borderRadius: BorderRadius.circular(16),
                        ),
                        child: Center(
                          child: heavyText(
                              "Show a Diagnosis", ColorResources.white, 18),
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          )),
    );
  }

  onsubmit() {
    zero = [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ];
    List<String> commonSymptomsString = [
      'fever',
      'headache',
      'throat sore',
      'shortness of breath',
      'cough'
    ];
    print(selectedSymptoms);
    print(commonSymptoms);
    for (int i = 0; i < selectedSymptoms.length; i++) {
      for (int j = 0; j < symptoms.length; j++) {
        if (symptoms[j] == selectedSymptoms[i]) {
          zero[j] = 1;
        }
      }
    }
    for (int i = 0; i < commonSymptoms.length; i++) {
      for (int j = 0; j < symptoms.length; j++) {
        if (symptoms[j] == commonSymptomsString[commonSymptoms[i]]) {
          zero[j] = 1;
        }
      }
    }
    log(zero.toString());
  }

  Widget HeaderWidget() {
    return Stack(
      alignment: Alignment.bottomCenter,
      clipBehavior: Clip.none,
      children: [
        Container(
          height: 160,
          width: Get.width,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.only(
              bottomLeft: Radius.circular(80),
              bottomRight: Radius.circular(80),
            ),
            gradient: LinearGradient(
              begin: Alignment.topCenter,
              end: Alignment.bottomCenter,
              colors: [
                ColorResources.green.withOpacity(0.2),
                ColorResources.lightBlue.withOpacity(0.2),
              ],
            ),
          ),
          child: Row(
            children: [
              Padding(
                padding: EdgeInsets.only(left: 10),
                child: InkWell(
                  onTap: () {
                    setState(() {
                      selectedSymptoms = [];
                      commonSymptoms = [];
                      empty = false;
                    });

                    Navigator.of(context).pop();
                  },
                  child: const Icon(Icons.arrow_back,
                      color: ColorResources.grey777),
                ),
              ),
              const SizedBox(width: 83),
              heavyText("Symptoms Search", ColorResources.green, 22,
                  TextAlign.center),
              Padding(
                padding: const EdgeInsets.only(left: 30, top: 1),
                child: InkWell(
                  onTap: () => () {
                    setState(() {
                      selectedSymptoms = [];
                      commonSymptoms = [];
                    });
                    Get.to(SignInScreen());
                  },
                  child: Container(
                    height: 40,
                    width: 40,
                    child: const Icon(Icons.logout_outlined,
                        color: ColorResources.grey777),
                  ),
                ),
              ),
            ],
          ),
        ),
        Positioned(
          bottom: -30,
          left: 24,
          right: 24,
          child: Container(
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(20),
            ),
          ),
        ),
      ],
    );
  }
}
